default_install_hook_types:
    - pre-commit
    - commit-msg

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: check-yaml
    -   id: check-toml
    -   id: check-json
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: no-commit-to-branch
        args: ["--pattern", "main", "--pattern", "^(?!feature/|chore/|bug/|hotfix/|release/).*$"]
-   repo: https://github.com/PyCQA/flake8
    rev: 7.2.0
    hooks:
    -   id: flake8
        language_version: python3.11
-   repo: https://github.com/compilerla/conventional-pre-commit
    rev: v4.0.0
    hooks:
    -   id: conventional-pre-commit
        stages: [commit-msg]
        args: []
